export const FETCH_RECORDS_REQUEST = 'FETCH_RECORDS_REQUEST';
export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS';
export const FETCH_RECORDS_FAILURE = 'FETCH_RECORDS_FAILURE';

export const FETCH_PRODUCTBYCATEGORY_REQUEST =
  'FETCH_PRODUCTBYCATEGORY_REQUEST';
export const FETCH_PRODUCTBYCATEGORY_SUCCESS =
  'FETCH_PRODUCTBYCATEGORY_SUCCESS';
export const FETCH_PRODUCTBYCATEGORY_FAILURE =
  'FETCH_PRODUCTBYCATEGORY_FAILURE';

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_ERROR = 'SAVE_DATA_ERROR';

export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR';

export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';

export const FREQUENTLY_BOUGHT_REQUEST = 'FREQUENTLY_BOUGHT_REQUEST';
export const FREQUENTLY_BOUGHT_SUCCESS = 'FREQUENTLY_BOUGHT_SUCCESS';
export const FREQUENTLY_BOUGHT_FAILURE = 'FREQUENTLY_BOUGHT_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const ORDER_HISTORY_REQUEST = 'ORDER_HISTORY_REQUEST';
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_FAILURE = 'ORDER_HISTORY_FAILURE';

export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE';

export const ORDER_PENDING_REQUEST = 'ORDER_PENDING_REQUEST';
export const ORDER_PENDING_SUCCESS = 'ORDER_PENDING_SUCCESS';
export const ORDER_PENDING_FAILURE = 'ORDER_PENDING_FAILURE';

export const ORDER_PLACED_REQUEST = 'ORDER_PLACED_REQUEST';
export const ORDER_PLACED_SUCCESS = 'ORDER_PLACED_SUCCESS';
export const ORDER_PLACED_FAILURE = 'ORDER_PLACED_FAILURE';

// actions/types.js or actions/productTypes.js
export const FETCH_SIMILAR_PRODUCTS_REQUEST = 'FETCH_SIMILAR_PRODUCTS_REQUEST';
export const FETCH_SIMILAR_PRODUCTS_SUCCESS = 'FETCH_SIMILAR_PRODUCTS_SUCCESS';
export const FETCH_SIMILAR_PRODUCTS_FAILURE = 'FETCH_SIMILAR_PRODUCTS_FAILURE';
export const UPDATE_SIMILAR_PRODUCTS_PAGE = 'UPDATE_SIMILAR_PRODUCTS_PAGE';
export const UPDATE_SIMILAR_PRODUCTS_LIMIT = 'UPDATE_SIMILAR_PRODUCTS_LIMIT';
export const RESET_SIMILAR_PRODUCTS = 'RESET_SIMILAR_PRODUCTS';
export const REACHED_END_SIMILAR_PRODUCTS = 'REACHED_END_SIMILAR_PRODUCTS';

// actions/types.js
export const FETCH_PRODUCTS_BY_CATEGORY_REQUEST =
  'FETCH_PRODUCTS_BY_CATEGORY_REQUEST';
export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS =
  'FETCH_PRODUCTS_BY_CATEGORY_SUCCESS';
export const FETCH_PRODUCTS_BY_CATEGORY_FAILURE =
  'FETCH_PRODUCTS_BY_CATEGORY_FAILURE';
export const UPDATE_PRODUCTS_BY_CATEGORY_PAGE =
  'UPDATE_PRODUCTS_BY_CATEGORY_PAGE';
export const UPDATE_PRODUCTS_BY_CATEGORY_LIMIT =
  'UPDATE_PRODUCTS_BY_CATEGORY_LIMIT';
export const RESET_PRODUCTS_BY_CATEGORY = 'RESET_PRODUCTS_BY_CATEGORY';
export const REACHED_END_PRODUCTS_BY_CATEGORY =
  'REACHED_END_PRODUCTS_BY_CATEGORY';

// actions/types.js or actions/productTypes.js
export const FETCH_RECENTLY_ADDED_PRODUCTS_REQUEST =
  'FETCH_RECENTLY_ADDED_PRODUCTS_REQUEST';
export const FETCH_RECENTLY_ADDED_PRODUCTS_SUCCESS =
  'FETCH_RECENTLY_ADDED_PRODUCTS_SUCCESS';
export const FETCH_RECENTLY_ADDED_PRODUCTS_FAILURE =
  'FETCH_RECENTLY_ADDED_PRODUCTS_FAILURE';
export const UPDATE_RECENTLY_ADDED_PRODUCTS_PAGE =
  'UPDATE_RECENTLY_ADDED_PRODUCTS_PAGE';
export const UPDATE_RECENTLY_ADDED_PRODUCTS_LIMIT =
  'UPDATE_RECENTLY_ADDED_PRODUCTS_LIMIT';
export const RESET_RECENTLY_ADDED_PRODUCTS = 'RESET_RECENTLY_ADDED_PRODUCTS';
export const REACHED_END_RECENTLY_ADDED_PRODUCTS =
  'REACHED_END_RECENTLY_ADDED_PRODUCTS';

// actions/types.js or actions/productTypes.js
export const FETCH_DISCOUNTED_PRODUCTS_REQUEST =
  'FETCH_DISCOUNTED_PRODUCTS_REQUEST';
export const FETCH_DISCOUNTED_PRODUCTS_SUCCESS =
  'FETCH_DISCOUNTED_PRODUCTS_SUCCESS';
export const FETCH_DISCOUNTED_PRODUCTS_FAILURE =
  'FETCH_DISCOUNTED_PRODUCTS_FAILURE';
export const UPDATE_DISCOUNTED_PRODUCTS_PAGE =
  'UPDATE_DISCOUNTED_PRODUCTS_PAGE';
export const UPDATE_DISCOUNTED_PRODUCTS_LIMIT =
  'UPDATE_DISCOUNTED_PRODUCTS_LIMIT';
export const RESET_DISCOUNTED_PRODUCTS = 'RESET_DISCOUNTED_PRODUCTS';
export const REACHED_END_DISCOUNTED_PRODUCTS =
  'REACHED_END_DISCOUNTED_PRODUCTS';

// actionTypes.js
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS';
export const UPDATE_SEARCH_PRODUCTS_PAGE = 'UPDATE_SEARCH_PRODUCTS_PAGE';
export const UPDATE_SEARCH_PRODUCTS_LIMIT = 'UPDATE_SEARCH_PRODUCTS_LIMIT';
export const REACHED_END_SEARCH_PRODUCTS = 'REACHED_END_SEARCH_PRODUCTS';

// orders types.js
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';

// inquiries types.js
export const CREATE_INQUIRY_REQUEST = 'CREATE_INQUIRY_REQUEST';
export const CREATE_INQUIRY_SUCCESS = 'CREATE_INQUIRY_SUCCESS';
export const CREATE_INQUIRY_FAILURE = 'CREATE_INQUIRY_FAILURE';

export const FETCH_INQUIRIES_REQUEST = 'FETCH_INQUIRIES_REQUEST';
export const FETCH_INQUIRIES_SUCCESS = 'FETCH_INQUIRIES_SUCCESS';
export const FETCH_INQUIRIES_FAILURE = 'FETCH_INQUIRIES_FAILURE';

// actionTypes.js for faqs
export const FETCH_FAQS_REQUEST = 'FETCH_FAQS_REQUEST';
export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_FAILURE = 'FETCH_FAQS_FAILURE';

// Action Types
export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE';

// Customer action types
export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

// BANNER actionTypes.js
export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_BANNERS_FAILURE = 'GET_BANNERS_FAILURE';

// PRODUCT DETAILS src/actions/actionTypes.js

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';

//get all products for homescreen
export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILURE = 'FETCH_ALL_PRODUCTS_FAILURE';
export const UPDATE_ALL_PRODUCTS_PAGE = 'UPDATE_ALL_PRODUCTS_PAGE';
export const UPDATE_ALL_PRODUCTS_LIMIT = 'UPDATE_ALL_PRODUCTS_LIMIT';
export const RESET_ALL_PRODUCTS = 'RESET_ALL_PRODUCTS';
export const REACHED_END_ALL_PRODUCTS = 'REACHED_END_ALL_PRODUCTS';

export const FETCH_ALL_CATEGORY_PRODUCTS_REQUEST =
  'FETCH_ALL_CATEGORY_PRODUCTS_REQUEST';
export const FETCH_ALL_CATEGORY_PRODUCTS_SUCCESS =
  'FETCH_ALL_CATEGORY_PRODUCTS_SUCCESS';
export const FETCH_ALL_CATEGORY_PRODUCTS_FAILURE =
  'FETCH_ALL_CATEGORY_PRODUCTS_FAILURE';
export const RESET_ALL_CATEGORY_PRODUCTS = 'RESET_ALL_CATEGORY_PRODUCTS';

export const FETCH_VENDORS_BY_CATEGORY_REQUEST =
  'FETCH_VENDORS_BY_CATEGORY_REQUEST';
export const FETCH_VENDORS_BY_CATEGORY_SUCCESS =
  'FETCH_VENDORS_BY_CATEGORY_SUCCESS';
export const FETCH_VENDORS_BY_CATEGORY_FAILURE =
  'FETCH_VENDORS_BY_CATEGORY_FAILURE';
export const RESET_VENDORS_BY_CATEGORY = 'RESET_VENDORS_BY_CATEGORY';
